### ISSUE TITLE
Shifts over Midnight from previous day are not shown in timeline

### ISSUE THREAD

**Issue by DaniGr** [coders4help/volunteer_planner#286]
Actual:
If I have a shift that runs from 11 p.m. to 2 a.m. it is only shown in the day it started but not in the day it ends.

Expected:
This shift should be shown in both days.

**Comment by srenatus** [comment]
No idea why github didn't pick it up, but with [this merge](https://github.com/coders4help/volunteer_planner/pull/295), this issue should be resolved (pending deployment, though).

**Comment by klinger** [comment]
371c908 solves the problem here? What commit is to merge? Or is the code yet to be written?

**Comment by srenatus** [comment]
#295 is merged, this can be closed.

**Comment by DaniGr** [comment]
This is only partially fixed: 
Shifts that go over to the next day are now shown on the previous day. But shifts that start on the previous day are not shown on the next day.

**Comment by Doca** [comment]
@christophmeissner could you clarify this with @DaniGr and turn this into a bug if its still not implemented on beta?

**Comment by klinger** [comment]
this is fixed on production, closed
